#undef TAPPING_TERM
#define TAPPING_TERM 174

#undef RGB_MATRIX_TIMEOUT
#define RGB_MATRIX_TIMEOUT 600000

#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 12

#define AUTO_SHIFT_TIMEOUT 135
#define CAPS_LOCK_STATUS
#define SERIAL_NUMBER "ArpMe/orAdEd"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

